<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OpenNest.Server.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../OpenNest.Data/OpenNest.Data.csproj" />
    <ProjectReference Include="../../OpenNest.IO/OpenNest.IO.csproj" />
  </ItemGroup>
</Project>
