<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OpenNest.IO</RootNamespace>
    <AssemblyName>OpenNest.IO</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="OpenNest.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenNest.Core\OpenNest.Core.csproj" />
    <ProjectReference Include="..\OpenNest.Engine\OpenNest.Engine.csproj" />
    <PackageReference Include="ACadSharp" Version="3.1.32" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
  </ItemGroup>
</Project>
