<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>OpenNest</RootNamespace>
    <AssemblyName>OpenNest.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Clipper2" Version="2.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>
</Project>
