<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\OpenNest.Core\OpenNest.Core.csproj" />
    <ProjectReference Include="..\..\OpenNest.IO\OpenNest.IO.csproj" />
  </ItemGroup>
</Project>
